version: "3"

services:
    db:
        image: mysql:8.0
        tty: true
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: false
            MYSQL_DATABASE: remind_me
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: rulli
            DB_HOST: db
            MYSQL_ROOT_HOST: "%"
            DB_PORT: 3306
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        networks:
            - mynetwork

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: remind_me
            DB_USERNAME: rulli
            DB_PASSWORD: password
        depends_on:
            - db
        command:
            - sh
            - -c
            - "sleep 10 && php artisan migrate:fresh && php artisan db:seed && php artisan serve --host=0.0.0.0"
        ports:
            - "9000:8000"
        networks:
            - mynetwork
    # web:
    #     image: nginx:alpine
    #     volumes:
    #         - /Users/rulli/pribadi/remindme-laravel/src/docker/nginx/:/etc/nginx/conf.d/
    #     ports:
    #         - "9000:80"
    #     depends_on:
    #         - app
    #     networks:
    #         - mynetwork
networks:
    mynetwork:
        driver: bridge
volumes:
    db:
        driver: local
